image:
  repository: "ghcr.io/code-tool/keepup-helm-scraper"
  tag: ""
  pullPolicy: IfNotPresent

cronjob:
  schedule: "0 */3 * * *"
  restartPolicy: Never

rbac:
  create: true

env:
  CLUSTER_NAME: ''
  API_TOKEN: ''
  API_URL: ''
  APP_ENV: prod
  RULES_FILE: /config/rules.yaml
